{% set name = "czml3" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1693475ba6b5e934daee6cd05a4ed3ac37fc68d1ca40dd17afe6c6f48fc914bc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - attrs >=19.2
    - python-dateutil >=2.7,<3
    - w3lib

test:
  imports:
    - czml3
    - czml3.enums
    - czml3.properties
    - czml3.types
    - czml3.widget

about:
  home: https://github.com/poliastro/czml3/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: czml3 is a Python library to write CZML

  dev_url: https://github.com/poliastro/czml3/

extra:
  recipe-maintainers:
    - astrojuanlu
